[package]
name = "day12"
version = "0.1.0"
authors = ["Roelant Ossewaarde <roelanto@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gnuplot = "0.0.32"
termion="1.1.1"
indexmap="1.3.0"
num="0.1.28"